Use Font Files instead of google fonts url for better performance.
m3ntorship/m3ntorship.com pull request #335
Opened 2020-08-28 12:40 UTC by AbdoMgdy

2020-08-28 21:53 UTC, elhaw reviewed
can we use three or four font files instead of adding them all?

2020-08-30 12:24 UTC, MAlngaawy reviewed
I deleted unused fonts files from the fonts folder and deleted its code from global.css. ( medium, thin )
it downed almost **from 290Kb To 140Kb**

2020-08-30 12:57 UTC, elhaw requested changes

2020-08-30 12:57 UTC, elhaw commented on frontend/styles/global.css
> +       url('../fonts/noto-sans-hk-v5-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
we can move the `fonts` folder inside the `public/static` path where we server all of our static files.
and change the path
Ex : ` url('../public/static/fonts/noto-sans-hk-v5-latin-regular.woff2') format('woff2'),`

2020-09-02 07:29 UTC, MAlngaawy commented
I just changed the fonts file position to be in the public -> static file
and change the font-face URL directory at global.css

2020-09-02 07:39 UTC, elhaw approved these changes
LGTM

2020-09-02 07:39 UTC, merged